### ISSUE TITLE
Who is going to take responsibility for this site

### ISSUE THREAD

**Issue by Azulan** [bitcoin-core/website#1]
Who are the site owners and what kind of FUD are they going to be posting to the detriment of the community?

**Comment by laanwj** [comment]
The site is going to be a communication channel for release information, blogs about work in progress, etc, for the Bitcoin Core project. Better communication from developers is often requested.

**Comment by Azulan** [comment]
Who are the site owners?

**Comment by Azulan** [comment]
The About page does not indicate any particular individual owners. Are we to understand that all core devs will take responsibility for this site? Are you unwilling to answer this question? If not, why not?

**Comment by btcdrak** [comment]
The content policy of the website can be seen [here](https://github.com/bitcoin-core/website/blob/gh-pages/CONTRIBUTING.md#content-policy).

**Comment by plasmoske** [comment]
The owners of the site are Theymos and his alter ego, Cobra.

**Comment by laanwj** [comment]
The ideal answer to the question "Who is going to take responsibility for this site" would be "the open source community around bitcoin core". That's the plan, of course, like anything around bitcoin, this is an experiment. But at least we're trying something instead of cynically posting to other projects' trackers.

**Comment by Azulan** [comment]
As if the bitcoin community hasn't had cause for cynicism lately.
